import type { Metadata } from "next";
import { Lilex, Gravitas_One } from "next/font/google";
import "../globals.css";

const lilex = Lilex({
  variable: "--font-lilex",
  subsets: ["latin"],
});

const gravitasOne = Gravitas_One({
  variable: "--font-gravitas-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-br"
      className={`${lilex.variable} ${gravitasOne.variable} h-full antialiased`}
    >
      
      <body className="min-h-dvh flex flex-col">
        {children}
      </body>
      
    </html>
  );
}
