import type { Metadata } from "next";
import { Lilex, Kumar_One } from "next/font/google";
import "./globals.css";

const lilex = Lilex({
  variable: "--font-lilex",
  subsets: ["latin"],
});

const kumarOne = Kumar_One({
  variable: "--font-kumar-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-br"
      className={`${lilex.variable} ${kumarOne.variable} h-full antialiased`}
    >
      <body className="min-h-dvh flex flex-col">{children}</body>
    </html>
  );
}
